"""Add Event model

Revision ID: 2af032d61f88
Revises: adc3c46cd3c6
Create Date: 2026-05-16 15:33:23.135244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af032d61f88'
down_revision = 'adc3c46cd3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('target_exercise_type', sa.String(length=50), nullable=False),
    sa.Column('target_sessions', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('participants_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('Friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Friendships', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('Events')
    # ### end Alembic commands ###
