"""Initial migration

Revision ID: fcd9c34faafd
Revises: 
Create Date: 2026-05-08 14:53:33.330064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd9c34faafd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Exercises',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_name', sa.String(length=50), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('units', sa.String(length=50), nullable=False),
    sa.Column('mean_statistic', sa.Float(), nullable=False),
    sa.Column('stdev_statistic', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Friendships',
    sa.Column('friendship_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_1'], ['Users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('friendship_id')
    )
    op.create_table('Logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stat_value', sa.Float(), nullable=False),
    sa.Column('standardised_score', sa.Float(), nullable=True),
    sa.Column('completed_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['Exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Logs')
    op.drop_table('Friendships')
    op.drop_table('Users')
    op.drop_table('Exercises')
    # ### end Alembic commands ###
